parent_config: https://raw.githubusercontent.com/uhooi/SwiftLint-Config/main/uhooi-base-swiftlint-config.yml

# 対象のファイル・フォルダ
included:
  - Shared
  - UhooiPicBook
  - UhooiPicBookStickers
  - UhooiPicBookWidgets
  - UhooiPicBookWidgetsConfigurableIntent
  #- UhooiPicBookTests
  #- UhooiPicBookUITests

# 対象外のファイル・フォルダ
excluded:
  - UhooiPicBook/Generated

