name: CI

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
      - Rambafile
  pull_request:
    branches:
      # - !master
      - develop
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
      - Rambafile

env:
  DEVELOPER_DIR: /Applications/Xcode_12.3.app

jobs:
  test:
    runs-on: macOS-latest
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # Xcodeのバージョン出力
    - name: Show Xcode version
      run: xcodebuild -version

    # Makeのバージョン出力
    - name: Show Make version
      run: make --version

    # Bundlerで管理しているライブラリのキャッシュ
    - name: Cache Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Bundlerで管理しているライブラリのインストール
    - name: Install Bundled Gems
      run: make install-bundler

    # Mintのインストール
    - name: Install Mint
      run: brew install mint

    # Mintで管理しているライブラリのキャッシュ
    - name: Cache Mint packages
      uses: actions/cache@v2
      with:
        path: mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    # Carthageで管理しているライブラリのキャッシュ
    - name: Cache Carthage packages
      uses: actions/cache@v2
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-

    # Carthageで管理しているライブラリのインストール
    - name: Install Carthage frameworks
      run: make install-carthage
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # ライセンス情報の生成、プロジェクトファイルの生成
    - name: Generate licenses and Xcode project
      run: make generate-licenses

    # ビルド
    - name: Xcode build
      run: make build-debug

    # ビルドログのアップロード
    - name: Upload build log Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: xcodebuild-logs
        path: xcodebuild_build.log
        if-no-files-found: ignore
        retention-days: 14

    # 単体テストの実行
    - name: Xcode test
      run: make test

    # 単体テストログのアップロード
    - name: Upload test log Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: xcodebuild-logs
        path: xcodebuild_test.log
        if-no-files-found: ignore
        retention-days: 14

  info:
    runs-on: macOS-latest

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # Xcodeの一覧出力
    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'

    # 端末の一覧出力
    - name: Show devices
      run: make show-devices
